# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='sensor',
            name='alias',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='sensor',
            name='blocked',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sensor',
            name='connected',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='sensor',
            name='paired',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='sensor',
            name='trusted',
            field=models.NullBooleanField(),
        ),
    ]
